## Week 3 Exercises

### Exercise 1

Use `math.gcd()` to create and print a list of all the primes up to 100. If a number is prime, then it is not divisible by all the smaller primes. Initialize your list with 2, start your search at 3, and use `list.append()` to add numbers to the list. You should use the function `max`.

In [5]:
import math 
primes = [2]
search = range(3,101)

for x in search:

    divisors = []
    for n in primes:
        divisors.append(math.gcd(x,n))
       
        
    if max(divisors) == 1:
        primes.append(x)
print(primes)            
    


[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


### Exercise 2

For the function $f(x) = 4\cos(3x)$, calculate the derivative and the approximation to the derivative $(f(x+h)-f(x-h))/(2h)$. Using $h=0.01$ find the maximum absolute difference between the derivative and the approximation for $x=[0,0.01,0.02,0.03,\dots,1.]$. You should use the functions `range`, `max` and `abs`.

In [15]:
#deriv = -12*math.sin(3*x)
#approx = (4*math.cos(3*(x + 0.01))-4*math.cos(3*(x -0.01)))/2*0.01
import math
import numpy as np
h = 0.01
difflist = [0]
def f(x):
    4*math.cos(3*x)

for x in np.arange(0,1, 0.01):
    deriv = -12*math.sin(3*x)
    approx = (4*math.cos(3*(x + 0.01))-4*math.cos(3*(x -0.01)))/2*0.01
    diff = abs(deriv)-abs(approx) 
    difflist.append(diff)

print(max(difflist))
    


11.998100892676732


### Exercise 3

The height of a projectile with initial position $x=0$, height $y=y_0$, speed $v=v_0$ and angle $\theta$ to the horizontal is given by $y(x) = x\tan(\theta)-\frac12 g(x/(v_0\cos(\theta))^2+y_0$, where $x$ is the horizontal position in m and $g$ is the acceleration of gravity. For $\theta = 45^\circ$, $v_0 = 10 ms^{-1}$, $g=9.81 ms^{-2}$ and $y_0 = 10 m$, print the height of the projectile at $x=[0,1,2,\dots,10]$.

In [7]:
import math as m
def h(x, yin, v, theta):
    y = x*m.tan(theta)-(1/2)*9.81*(x/(v*m.cos(theta)))**2+yin
    
    print(round(y,5))
yin = 10
v = 10
theta = m.radians(45)
for x in range(0,11):
    print(f"At x(m): ", x, ", height(m) is:  ")
    h(x,yin,v,theta) 
    
    


    

At x(m):  0 , height(m) is:  
10.0
At x(m):  1 , height(m) is:  
10.9019
At x(m):  2 , height(m) is:  
11.6076
At x(m):  3 , height(m) is:  
12.1171
At x(m):  4 , height(m) is:  
12.4304
At x(m):  5 , height(m) is:  
12.5475
At x(m):  6 , height(m) is:  
12.4684
At x(m):  7 , height(m) is:  
12.1931
At x(m):  8 , height(m) is:  
11.7216
At x(m):  9 , height(m) is:  
11.0539
At x(m):  10 , height(m) is:  
10.19


### Exercise 4

Create a (3,3) array, $E$, which has values of 1 on the main diagonal, i.e., where the row and column number are the same, and values of 0 everywhere else. You should be able to do this using `np.array()` and `np.zeros()`. Create an arbitrary (3,3) matrix and a vector of length 3, and confirm that multiplying these arrays by $E$ does not change the arrays.

In [17]:
import numpy as np
E = np.array([[1,0,0], [0,1,0],[0,0,1]])

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([3, 2, 1])

testprod1 = E @ matrix
testprod2 = E @ vector

print(matrix)
print(testprod1)
print(vector) 
print(testprod2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 2 1]
[3 2 1]


### Exercise 5

Repeat Exercise 3, but use `np.linspace()` to create 21 evenly spaced values of $x$ in the range $0\le x\le 10$. You should not need to use a loop to calculate the $y$ values.


In [18]:
import math as m
import numpy as np
def h(x, yin, v, theta):
    y = x*m.tan(theta)-(1/2)*9.81*(x/(v*m.cos(theta)))**2+yin
    
    print("X: ", x)
    print("Y: ", y)
    
yin = 10
v = 10
theta = m.radians(45)
x = np.linspace(0,10,21)

h(x,yin,v,theta)
    



X:  [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]
Y:  [10.       10.475475 10.9019   11.279275 11.6076   11.886875 12.1171
 12.298275 12.4304   12.513475 12.5475   12.532475 12.4684   12.355275
 12.1931   11.981875 11.7216   11.412275 11.0539   10.646475 10.19    ]
